export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LIST = "SET_USER_LIST";
export const USERS_LOADING = "USERS_LOADING";
export const FEEDBACK_LIST = "FEEDBACK_LIST";
export const NEW_FEEDBACK = "NEW_FEEDBACK";